backend/src/main/java/com/funding/backend/domain/project/entity/Project.java, backend/src/main/java/com/funding/backend/domain/purchaseCategory/entity/PurchaseCategory.java
구매 카테고리 연관관계 오류 해결
<br>
#6 
<br>
구매 카테고리 연관관계 오류 해결 
<br>
=> [ fix ] 6: 구매 카테고리 연관관계 오류 해결

backend/docker-compose.yml
docker 파일 추가 
<br>
#10 
<br>
docker compose 추가
mysql, redis 사용 가능
<br>
=> [ feat ] : 10 docker 파일 추가

backend/src/main/java/com/funding/backend/domain/option/controller/OptionController.java, backend/src/main/java/com/funding/backend/domain/option/dto/request/OptionRequestDto.java, backend/src/main/java/com/funding/backend/domain/option/dto/response/OptionResponseDto.java, backend/src/main/java/com/funding/backend/domain/option/repository/OptionRepository.java, backend/src/main/java/com/funding/backend/domain/option/service/OptionService.java, backend/src/main/java/com/funding/backend/domain/project/dto/request/PurchaseOptionDto.java, backend/src/main/java/com/funding/backend/domain/project/dto/request/PurchaseProjectDetail.java, backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/controller/OptionController.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/dto/request/PurchaseOptionRequestDto.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/dto/response/OptionResponseDto.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/entity/PurchaseOption.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/repository/PurchaseOptionRepository.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/service/OptionService.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/service/PurchaseOptionService.java
구매옵션 생성, 수정 기능 구현 완료 
<br>
#13 
<br>
구매 옵션 생성, 수정 구현 
<br>
=> [ feat ] 13 : 구매 옵션 생성, 수정 구현

backend/src/main/java/com/funding/backend/domain/pricingPlan/entity/PricingPlan.java, backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java, backend/src/main/java/com/funding/backend/domain/project/dto/request/ProjectCreateRequestDto.java, backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java, backend/src/main/java/com/funding/backend/domain/projectImage/entity/ProjectImage.java, backend/src/main/java/com/funding/backend/domain/purchase/controller/PurchaseController.java, backend/src/main/java/com/funding/backend/domain/purchase/dto/request/PurchaseOptionDto.java, backend/src/main/java/com/funding/backend/domain/purchase/dto/request/PurchaseOptionRequestDto.java, backend/src/main/java/com/funding/backend/domain/purchase/dto/request/PurchaseProjectDetail.java, backend/src/main/java/com/funding/backend/domain/purchase/dto/request/PurchaseRequestDto.java, backend/src/main/java/com/funding/backend/domain/purchase/dto/request/PurchaseUpdateRequestDto.java, backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java, backend/src/main/java/com/funding/backend/domain/purchaseCategory/repository/PurchaseCategoryRepository.java, backend/src/main/java/com/funding/backend/domain/purchaseCategory/service/PurchaseCategoryService.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/controller/OptionController.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/entity/PurchaseOption.java, backend/src/main/java/com/funding/backend/domain/purchaseOption/service/PurchaseOptionService.java, backend/src/main/java/com/funding/backend/global/config/MultipartJackson2HttpMessageConverter.java, backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java, backend/src/main/java/com/funding/backend/global/exception/GlobalExceptionHandler.java, backend/src/main/java/com/funding/backend/global/utils/s3/ImageService.java, backend/src/main/java/com/funding/backend/global/utils/s3/S3FileInfo.java, backend/src/main/java/com/funding/backend/global/utils/s3/S3Uploader.java, backend/src/main/java/com/funding/backend/global/validator/ProjectDetailValidator.java, backend/src/main/java/com/funding/backend/global/validator/annotaion/ValidProjectDetail.java
구매 프로젝트 생성시, 이미지 처리, 구매 옵션 파일 처리 
<br>
#19 
<br>
- multipart/form-data 형식으로 JSON + 파일을 함께 전송
- 이미지/파일을 AWS S3에 업로드 (ACL 설정 이슈 대응 포함)
- @RequestPart로 DTO + 파일 리스트 함께 처리
- Swagger, Postman 등에서도 테스트 가능하게 설정
| 필드명          | 타입           | 설명 |
|----------------|----------------|------|
| `requestDto`   | string (JSON)  | 프로젝트 생성 요청 DTO (JSON 문자열) |
| `contentImage` | file[]         | 본문 이미지 파일 리스트 (선택) |
| `optionFiles`  | file[]         | 구매 옵션과 연결된 파일 리스트 (선택) |
<br>
```json
{
"projectType": "PURCHASE",
"title": "AI 개발자를 위한 포트폴리오 템플릿",
"introduce": "개발자들이 빠르게 포트폴리오를 만들 수 있도록 돕는 템플릿입니다.",
"content": "Notion 기반 템플릿으로 다양한 포지션에 맞게 구성되어 있습니다.",
"field": "웹 개발",
"pricingPlanId": 7,
"purchaseDetail": {
"providingMethod": "DOWNLOAD",
"gitAddress": …
```
=> [ feat ] 19 : 구매 프로젝트 생성에 이미지 처리

backend/src/main/java/com/funding/backend/domain/like/controller/LikeController.java, backend/src/main/java/com/funding/backend/domain/like/dto/request/LikeRequestDto.java, backend/src/main/java/com/funding/backend/domain/like/dto/response/LikeResponseDto.java, backend/src/main/java/com/funding/backend/domain/like/entity/Like.java, backend/src/main/java/com/funding/backend/domain/like/repository/LikeRepository.java, backend/src/main/java/com/funding/backend/domain/like/service/LikeService.java
좋아요를 토글로 구현하였습니다.
좋아요 여부, 좋아요 수, 좋아한 프로젝트 목록 조회 기능 구현했습니다.
<br>
- #28 
<br>
- `POST` /api/v1/like/project/{projectId}: 좋아요를 토글합니다.
- `GET` /api/v1/like/project/{projectId}/liked: 프로젝트의 좋아요 여부를 조회합니다.
- `GET` /api/v1/like/project/{projectId}/count: 프로젝트의 좋아요 수를 조회합니다.
- `GET` /api/v1/like/project: 내가 좋아요한 프로젝트 목록들을 조회합니다.
=> [ Feat ] 28 : 좋아요 기능 구현

backend/src/main/java/com/funding/backend/domain/project/dto/request/ProjectCreateRequestDto.java, backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java, backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java, backend/src/main/resources/application.yml
작물 프로젝트 생성 시 유저 식별 기능을 추가하여, 프로젝트를 생성한 사용자를 명확히 추적하고 식별할 수 있도록 구현했습니다.
<br>
#42 
<br>
- 창작물 프로젝트 생성 시 User 정보 연동
- 유저 식별을 위한 인증 기반 로직 추가
- DB에 user_id와 함께 프로젝트 저장되도록 처리
<br>
=> [ feat ] 42 : 창작물 프로젝트 생성시 유저 식별 기능 추가

backend/src/main/java/com/funding/backend/domain/user/controller/UserController.java, backend/src/main/java/com/funding/backend/security/jwt/TokenService.java, backend/src/main/java/com/funding/backend/security/oauth/model/CustomOAuth2User.java, backend/src/main/java/com/funding/backend/security/oauth/provider/GithubOAuthUserParser.java, backend/src/main/java/com/funding/backend/security/oauth/provider/KakaoOAuthUserParser.java
응답형식 통일 및 예외처리 통일
<br>
#54 
> closed #54 
<br>
제가 작업한 기능에 대한 
- api 응답형식 통일 
- 예외처리 통일
<br>
=> [ refact ] : 54 응답형식 통일 및 예외처리 통일

backend/src/main/resources/application-local.yml, backend/src/main/resources/application.yml
소셜로그인 오류 수정 
<br>
#59 
<br>
custom.site.backUrl 연결 안되는 문제 해결 
<br>
=> [ fix ] : 59 소셜로그인 수정

backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java, backend/src/main/java/com/funding/backend/domain/project/dto/response/ProjectSearchResponseDto.java, backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java, backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java, backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
프로젝트 제목 기반 검색 기능으로 두 글자 이상 일치하면 결과 노출
<br>
#76 
> closed #76 
<br>
- 구매형 프로젝트만 결과노출, 후원형 반영 후 업데이트 예정
<br>
=> [ feat ] 76 :  검색 기능 구현

backend/src/main/java/com/funding/backend/domain/donation/entity/Donation.java, backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java, backend/src/main/java/com/funding/backend/domain/project/dto/request/PopularProjectRequestDto.java, backend/src/main/java/com/funding/backend/domain/project/dto/response/PopularProjectResponseDto.java, backend/src/main/java/com/funding/backend/domain/project/dto/response/ReviewProjectResponseDto.java, backend/src/main/java/com/funding/backend/domain/project/dto/response/UnderReviewProjectResponseDto.java, backend/src/main/java/com/funding/backend/domain/project/entity/Project.java, backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java, backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java, backend/src/main/java/com/funding/backend/enums/PopularProjectSortType.java, backend/src/main/java/com/funding/backend/enums/ProjectStatus.java, backend/src/main/java/com/funding/backend/enums/ProjectTypeFilter.java, backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
인기 프로젝트 조회 기능 추가
<br>
- #75 
<br>
- 검색 조건(인기 정렬 조건, 프로젝트 타입) 설정
- 프로젝트 조회 기능 구현
=> [ Feat ] 75 : 인기 프로젝트 조회 기능 추가

backend/src/main/java/com/funding/backend/security/oauth/OAuth2LoginSuccessHandler.java
소셜로그인 리다이렉트 url 설정 추가 
<br>
#86 
<br>
<br>
=> [ fix ] 86 : 소셜로그인 설정

backend/src/main/java/com/funding/backend/security/oauth/OAuth2LoginSuccessHandler.java
frontRedirectUrl로 수정
<br>
#86 
<br>
<br>
=> [ fix ] 86 : frontRedirectUrl로 수정

backend/src/main/java/com/funding/backend/security/jwt/TokenService.java
유저 정보 조회 변경
<br>
#96 
<br>
유저 정보 조회 변경
<br>
=> [ refact ] 96 : 유저 정보 조회 변경

backend/src/main/java/com/funding/backend/global/config/WebConfig.java
cors 형식 수정
<br>
#102 
<br>
cors 형식 수정
<br>
=> [ fix ] 102 : cors 형식 수정

backend/src/main/java/com/funding/backend/security/jwt/TokenService.java, backend/src/main/java/com/funding/backend/security/oauth/OAuth2LoginSuccessHandler.java
sameSite 변경
<br>
#110 
<br>
sameSite 변경
<br>
=> [ fix ] 110 : sameSite 변경

backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java, backend/src/main/java/com/funding/backend/security/jwt/TokenService.java, backend/src/main/java/com/funding/backend/security/oauth/OAuth2LoginSuccessHandler.java
sameSite변경 
<br>
<br>
sameSite변경 
<br>
=> [ merge ] : dev코드 main에 병합 

backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
<br>
#86 
<br>
securityConfig 수정
.anyRequest().authenticated() 추가 
<br>
=> [ fix ] : 86 securityConfig 수정

backend/src/main/java/com/funding/backend/security/oauth/OAuth2LoginSuccessHandler.java
카카오 로그인 해결 
<br>
<br>
카카오 로그인 해결 
<br>
=> [ merge ] : dev 코드 병합 

backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java, backend/src/main/java/com/funding/backend/security/oauth/OAuth2LoginSuccessHandler.java, backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java, backend/src/main/java/com/funding/backend/security/oauth/resolver/CustomAuthorizationRequestResolver.java
dev코드 main에 병합
<br>
#110 
<br>
dev코드 main에 병합
<br>
=> [ merge ] : dev코드 main에 병합

backend/src/main/java/com/funding/backend/global/config/PermitUrl.java, backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
시큐리티 필터 허용 url 
<br>
#125
<br>
시큐리티 필터 허용 url 
<br>
=> [ feat ] 125 : 시큐리티 필터 허용 url 

backend/src/main/java/com/funding/backend/security/jwt/TokenService.java, backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
로그인 헤더 추가
<br>
#127 
<br>
로그인 헤더 추가
<br>
=> [ feat ] 127 : 로그인 헤더 추가

backend/src/main/java/com/funding/backend/security/jwt/TokenService.java, backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
dev 코드 메인에 병합 
<br>
<br>
dev 코드 메인에 병합 
<br>
=> [ merge ] : dev 코드 메인에 병합 

backend/src/main/java/com/funding/backend/global/config/PermitUrl.java
임시 테스트 유저 토큰 url 추가
<br>
#130 
<br>
임시 테스트 유저 토큰 url 추가
<br>
=> [ feat ] 130 : 임시 테스트 유저 토큰 url 추가

backend/src/main/java/com/funding/backend/security/jwt/TokenService.java
헤더에서도 쿠키 빼오게
<br>
#136 
<br>
헤더에서도 쿠키 빼오게
<br>
=> [ feat ] 136 : 헤더에서도 쿠키 빼오게

backend/src/main/java/com/funding/backend/global/config/PermitUrl.java, backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
cors 설정 추가
<br>
#139 
<br>
cors 설정 추가
<br>
=> [ feat ] 139 : cors 설정 추가

backend/src/main/java/com/funding/backend/domain/purchase/dto/response/PurchaseResponseDto.java
구매 프로젝트 응답 코드 추가
<br>
#145 
<br>
구매 프로젝트 응답 코드 추가
<br>
=> [ refact ] 145 : 구매 프로젝트 응답 코드 추가

backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java, backend/src/main/java/com/funding/backend/domain/project/dto/response/PurchaseProjectResponseDto.java, backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java, backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java, backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java, backend/src/main/java/com/funding/backend/domain/user/controller/UserController.java, backend/src/main/java/com/funding/backend/domain/user/service/UserService.java, backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
구매 프로젝트 응답 형식에 유저 정보 포함 
<br>
#148 
<br>
구매 프로젝트 응답 형식에 유저 정보 포함 
<br>
=> [ feat ] 148 : 구매 프로젝트 응답 형식에 유저 정보 포함 

backend/src/main/java/com/funding/backend/security/jwt/JwtTokenizer.java
토큰 유효시간 연장 3시간
<br>
#151 
<br>
토큰 유효시간 연장 3시간으로 수정 
<br>
=> [ refact ] 151 : 토큰 유효시간 연장 3시간

backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java, backend/src/main/java/com/funding/backend/security/jwt/JwtTokenizer.java
dev 코드 main에 병합 
<br>
<br>
dev 코드 main에 병합 
<br>
=> [ merge ] : dev 코드 main에 병합 

backend/src/main/java/com/funding/backend/security/jwt/TokenService.java, backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
카카오 쿠키 해결
<br>
#156 
<br>
카카오 쿠키 해결
<br>
=> [ feat ] 156 : 카카오 쿠키 해결

.github/workflows/deploy.yml, .gitignore, backend/src/main/java/com/funding/backend/global/config/SwaggerConfig.java, docker-compose.override.yml, docker-compose.yml, nginx/Dockerfile, nginx/nginx.conf, nginx/nginx.local.conf
https 환경 구성
<br>
- #155 
<br>
nginx 컨테이너 추가
nginx 설정 추가
=> [ Deploy ] 155 : https 환경 구성

backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
카카오 로그인 구현
<br>
<br>
카카오 로그인 구현
<br>
=> [ feat ] 168 : 카카오 로그인 구현

backend/src/main/java/com/funding/backend/domain/follow/dto/response/FollowResponseDto.java, backend/src/main/java/com/funding/backend/domain/follow/repository/FollowRepository.java
[ feat ] 164  팔로우 목록 필드 추가
<br>
#164 
<br>
팔로우 목록 보기
- user_id, name, image(프사), introduce
<br>
=> [ feat ] 164  팔로우 목록 필드 추가

backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
카카오 쿠키 생성 시 dameSite None으로
<br>
#168
<br>
카카오 쿠키 생성 시 dameSite None으로
<br>
=> [ feat ] 168 : 카카오 쿠키 생성 시 dameSite None으로

docker-compose.override.yml, docker-compose.yml
dev 코드 main에 merge 
<br>
<br>
dev 코드 main에 merge 
<br>
=> [ merge ] : dev 코드 main에 merge 

backend/src/main/java/com/funding/backend/global/config/PermitUrl.java
- qna와 후기의 조회 권한을 전체로 변경(후기) 및 추가(qna)
<br>
#157 
> closed #157 
<br>
<br>
=> [ refact ] 157 : qna, review permitUrl 추가

backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java
=> [ refact ] 187 : 조회 url 수정

backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
: 프로젝트, 구매옵션 cors 추가
<br>
<br>
: 프로젝트, 구매옵션 cors 추가
<br>
=> [ fix ] 202 : 프로젝트, 구매옵션 cors 추가

backend/src/main/java/com/funding/backend/security/jwt/TokenService.java
httpsOnly 끄기
<br>
<br>
httpsOnly 끄기
<br>
=> [ feat ] : httpsOnly 끄기

backend/src/main/java/com/funding/backend/domain/alarm/controller/AlarmController.java, backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java, backend/src/main/java/com/funding/backend/security/jwt/JwtAuthFilter.java, backend/src/main/java/com/funding/backend/security/jwt/dto/response/TokenResponseDto.java, backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java, backend/src/main/java/com/funding/backend/security/oauth/resolver/CustomAuthorizationRequestResolver.java
: 접근 권한 추가
프론트 접근 cors 수정 추가 
<br>
#205 
<br>
프론트 접근 cors 수정 추가 
<br>
=> [ feat ] 205 : 프론트 접근 cors 수정 추가 

backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
cors url 공백 수정
<br>
#225 
<br>
cors url 공백 수정
<br>
=> [ fix ] 225: cors url 공백 수정

backend/src/main/java/com/funding/backend/global/config/RedisConfig.java, backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java, backend/src/main/java/com/funding/backend/security/controller/AuthController.java, backend/src/main/java/com/funding/backend/security/jwt/TokenService.java, backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
refreshToken으로 accessToken api 호출 redis 사용 
<br>
#215 
<br>
refreshToken으로 accessToken api 호출 redis 사용 
<br>
=> [ fix ] 215 : refreshToken으로 accessToken api 호출 redis 사용 

backend/src/main/java/com/funding/backend/security/jwt/JwtAuthFilter.java
refreshToken 추가
<br>
#230 
<br>
refreshToken 추가
<br>
=> [ fix ] 230 : refreshToken 추가

backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
소셜 로그인 쿠키 포함
<br>
<br>
소셜 로그인 쿠키 포함
<br>
=> [ fix ] 233 : 소셜 로그인 쿠키 포함

backend/src/main/java/com/funding/backend/security/jwt/JwtAuthFilter.java
filter 오류로 인한 구매 프로젝트 생성 오류 해결 
<br>
#241 
<br>
filter 오류로 인한 구매 프로젝트 생성 오류 해결 
<br>
=> [ fix ] 241 : 구매 프로젝트 생성 인증 오류 해결 

backend/src/main/java/com/funding/backend/domain/order/repository/OrderRepository.java, backend/src/main/java/com/funding/backend/domain/order/service/OrderService.java, backend/src/main/java/com/funding/backend/domain/project/entity/Project.java, backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java, backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java, backend/src/main/java/com/funding/backend/domain/purchase/controller/PurchaseController.java, backend/src/main/java/com/funding/backend/domain/purchase/dto/response/PurchaseListResponseDto.java, backend/src/main/java/com/funding/backend/domain/purchase/repository/PurchaseRepository.java, backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
내가 생성한 구매형 프로젝트 리스트 조회
<br>
#252 
<br>
내가 생성한 구매형 프로젝트 리스트 조회
<br>
=> [ feat ] 252 : 내가 생성한 구매형 프로젝트 리스트 조회

backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
[ fix ] 237 쿠키에 액세스,리프레시 토큰
<br>
#237 
> closed #237 
<br>
기존: 쿠키에 액세스토큰 담아 전송 
수정: 쿠키에 액세스, 리프레시 토큰 담아 전송 
<br>
=> [ fix ] 237 쿠키에 액세스,리프레시 토큰

backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationMilestoneRequestDto.java, backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationProjectDetail.java, backend/src/main/java/com/funding/backend/domain/donation/entity/Donation.java, backend/src/main/java/com/funding/backend/domain/donation/repository/DonationRepository.java, backend/src/main/java/com/funding/backend/domain/donation/service/DonationProjectService.java, backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java, backend/src/main/java/com/funding/backend/domain/donationMilestone/controller/DonationMilestoneController.java, backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/request/DonationMilestoneCreateDto.java, backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/request/DonationMilestoneUpdateDto.java, backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/response/DonationMilestoneDto.java, backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/response/DonationMilestoneResponseDto.java, backend/src/main/java/com/funding/backend/domain/donationMilestone/entity/DonationMilestone.java, backend/src/main/java/com/funding/backend/domain/donationMilestone/repository/DonationMilestoneRepository.java, backend/src/main/java/com/funding/backend/domain/donationMilestone/service/DonationMilestoneService.java, backend/src/main/java/com/funding/backend/domain/project/dto/response/DonationProjectResponseDto.java, backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java, backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
- 후원 프로젝트 생성 시 마일스톤(개발 예정 일정) 필드 기능 구현
<br>
#250 
<br>
<br>
=> [ feat ] 250 : 후원 프로젝트 생성 시 마일스톤(로드맵) 기능 구현

backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
sse를 위한 추가 헤더 설정
<br>
<br>
sse를 위한 추가 헤더 설정
<br>
=> [ fix ] 271 : sse를 위한 추가 헤더 설정

nginx/nginx.conf, nginx/nginx.local.conf
sse를 위한 nginx 설정 추가
<br>
#274 
<br>
sse를 위한 nginx 설정 추가
<br>
=> [ deploy ] 274 : sse를 위한 nginx 설정 추가

backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java, nginx/nginx.conf, nginx/nginx.local.conf
sse를 위한 nginx 설정 추가 
<br>
<br>
sse를 위한 nginx 설정 추가 
<br>
=> [ merge ] : dev 코드 main 병합 

nginx/nginx.conf, nginx/nginx.local.conf
sse 내부 연결 수정
<br>
#277 
<br>
sse 내부 연결 수정
<br>
=> [ deploy ] 277 : sse 내부 연결 수정

backend/src/main/resources/application.yml
yml 파일 정산 정보 추가
<br>
#287 
<br>
yml 파일 정산 정보 추가
<br>
=> [ feat ] 287 : yml 파일 정산 정보 추가

backend/src/main/java/com/funding/backend/domain/donation/dto/response/DonationListResponseDto.java, backend/src/main/java/com/funding/backend/domain/donation/repository/DonationRepository.java, backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java, backend/src/main/java/com/funding/backend/domain/purchase/dto/response/PurchaseListResponseDto.java
- 내가 생성한 프로젝트 목록 조회 Dto 수정
- #308 
<br>
<br>
=> [ feat ] 308 :  내가 생성한 프로젝트 목록 조회 Dto 수정

backend/src/main/java/com/funding/backend/domain/settlement/controller/SettlementController.java, backend/src/main/java/com/funding/backend/domain/settlement/dto/response/SettlementDetailListResponseDto.java, backend/src/main/java/com/funding/backend/domain/settlement/dto/response/SettlementDetailResponseDto.java, backend/src/main/java/com/funding/backend/domain/settlement/dto/response/SettlementMonthlyTotalResponseDto.java, backend/src/main/java/com/funding/backend/domain/settlement/mapper/SettlementDetailListResponseMapper.java, backend/src/main/java/com/funding/backend/domain/settlement/mapper/SettlementDetailResponseMapper.java, backend/src/main/java/com/funding/backend/domain/settlement/repository/SettlementRepository.java, backend/src/main/java/com/funding/backend/domain/settlement/service/SettlementService.java
유저 총 정산 내역
<br>
#311 
<br>
유저 총 정산 내역
<br>
=> [ feat ] 311 : 유저 총 정산 내역

backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java, backend/src/main/java/com/funding/backend/security/filter/UserStatusCheckFilter.java
신고 3회 이상 사용자 로그인시 페이지 제한
<br>
#336 
> closed #336 
<br>
신고 3회 이상 사용자 로그인시 페이지 제한
- login 페이지만 허용됨
<br>
=> [ feat ] 336 신고 3회 이상 사용자 로그인시 페이지 제한
